name: drf_client
description: A complete REST API client with authentication for Django Rest Framework based backends
version: 0.0.6
homepage: https://github.com/Otajonov/drf_client
license: MIT


environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  app_links: ^6.1.1
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  http: ^1.1.0
  oauth2: ^2.0.2
  url_launcher: ^6.2.5
  win32_registry: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
